<?php
defined('BASEPATH') OR exit('No direct script access allowed');

class WB_Calendar extends CI_Calendar
{
    protected  $_url = '';
    protected $prefs = [
        'start_day' => 'sunday',
        'month_type' => 'long',
        'day_type' => 'short',
        'show_next_prev' => true,
        'show_other_days' => false,
    ];

    public function __construct()
    {
        $template = $this->_setTemplate();
        $this->prefs['template'] = $template;
        parent::__construct($this->prefs);
    }

    public function generate($year = '', $month = '', $data = array())
    {
        return parent::generate($year, $month, $data); // TODO: Change the autogenerated stub
    }

    private function _setTemplate()
    {
        return '
            {table_open}
            <table border="0" cellpadding="0" cellspacing="0" class="calendar NG">
            <colgroup>
                <col style="width: 14.28%"/>
                <col style="width: 14.28%"/>
                <col style="width: 14.28%"/>
                <col style="width: 14.28%"/>
                <col style="width: 14.28%"/>
                <col style="width: 14.28%"/>
                <col style="width: 14.28%"/>
            </colgroup>
            {/table_open}    
    
            {heading_row_start}
            <thead>
            <tr class="calendar_month">
            <th colspan="7" class="">
            {/heading_row_start}
    
            {heading_previous_cell}
            <span class="prev"><a="javascript:void(0)" onclick="show_calendar(\'{previous_url}\')" style="cursor:pointer"><img src="'.img_url('counsel/calendar_prev.png').'"></a></span>
            {/heading_previous_cell}
            
            {heading_title_cell}{heading}{/heading_title_cell}
            
            {heading_next_cell}
            <span class="next"><a="javascript:void(0)" onclick="show_calendar(\'{next_url}\')" style="cursor:pointer"><img src="'.img_url('counsel/calendar_next.png').'"></a></span>
            {/heading_next_cell}
    
            {heading_row_end}
            </th>
            </tr>
            </thead>
            {/heading_row_end}
            
            {week_row_start}<tr class="calendar_week">{/week_row_start}
            {week_day_cell}<td>{week_day}</td>{/week_day_cell}
            {week_row_end}</tr>{/week_row_end}
    
            {cal_row_start}<tr class="calendar_day">{/cal_row_start}
            {cal_cell_start}<td>{/cal_cell_start}
            {cal_cell_start_today}<td>{/cal_cell_start_today}
            {cal_cell_start_other}<td>&nbsp;{/cal_cell_start_other}
    
            {cal_cell_content}{day}{content}{/cal_cell_content}
            {cal_cell_content_today}{day}{content}{/cal_cell_content_today}
    
            {cal_cell_no_content}{day}{/cal_cell_no_content}
            {cal_cell_no_content_today}<div class="highlight">{day}</div>{/cal_cell_no_content_today}
            {cal_cell_blank}&nbsp;{/cal_cell_blank}
            {cal_cell_other}{day}{cal_cel_other}
    
            {cal_cell_end}</td>{/cal_cell_end}
            {cal_cell_end_today}</td>{/cal_cell_end_today}
            {cal_cell_end_other}</td>{/cal_cell_end_other}
            {cal_row_end}</tr>{/cal_row_end}
    
            {table_close}</table>{/table_close}
        ';
    }
}